# Generated by Django 4.2 on 2023-04-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('NumeroCuenta', models.CharField(max_length=255, unique=True)),
                ('FechaVencimientoPago', models.DateField()),
                ('MontoDeuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MontoPago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Estado', models.BooleanField(default=False)),
            ],
        ),
    ]
