# Generated by Django 4.2 on 2023-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioEducacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaAlumnos',
            fields=[
                ('CodigoAlumno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('FechaVencimientoPago', models.DateField()),
                ('MontoDeuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MontoPago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CuentaAlumnos',
            },
        ),
        migrations.DeleteModel(
            name='tbAlumno',
        ),
    ]
