# Generated by Django 4.2 on 2023-04-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioEducacion', '0002_cuentaalumnos_delete_tbalumno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CuentaAlumnos',
            new_name='CuentAlumnos',
        ),
        migrations.AlterModelTable(
            name='cuentalumnos',
            table='CuentAlumnos',
        ),
    ]
