# Generated by Django 4.2 on 2023-04-29 08:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioEducacion', '0003_rename_cuentaalumnos_cuentalumnos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbAlumno',
            fields=[
                ('CodigoAlumno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbAlumno',
            },
        ),
        migrations.CreateModel(
            name='tbDeudasAlumno',
            fields=[
                ('CodigoDeuda', models.AutoField(primary_key=True, serialize=False)),
                ('CantidadDeuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FechaVencimiento', models.DateField()),
                ('Estado', models.BooleanField(default=False)),
                ('fkCodigoAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicioEducacion.tbalumno')),
            ],
            options={
                'db_table': 'tbDeudasAlumno',
            },
        ),
        migrations.CreateModel(
            name='tbPagosAlumno',
            fields=[
                ('CodigoPago', models.AutoField(primary_key=True, serialize=False)),
                ('MontoPago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('FechaPago', models.DateField(default=datetime.date.today)),
                ('FKCodigoDeuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicioEducacion.tbdeudasalumno')),
            ],
            options={
                'db_table': 'tbPagosAlumno',
            },
        ),
        migrations.DeleteModel(
            name='CuentAlumnos',
        ),
    ]
