# Generated by Django 4.2 on 2023-07-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioEducacion', '0004_tbalumno_tbdeudasalumno_tbpagosalumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbCuenta',
            fields=[
                ('CodigoCuenta', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Divisa', models.CharField(max_length=255)),
                ('fkCodigoAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicioEducacion.tbalumno')),
            ],
            options={
                'db_table': 'tbCuenta',
            },
        ),
    ]
