# Generated by Django 4.2 on 2023-04-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('costo_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minutos_incluidos', models.IntegerField()),
                ('datos_incluidos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='Desconocido', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicio_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.plan')),
            ],
        ),
    ]
