# Generated by Django 4.2 on 2023-04-29 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbClientes',
            fields=[
                ('CodigoCliente', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Ciudad', models.CharField(max_length=255)),
                ('Telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'TbClientes',
            },
        ),
        migrations.CreateModel(
            name='TbDeuda',
            fields=[
                ('CodigoDeuda', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('FechaVencimientoPago', models.DateField()),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estado', models.CharField(max_length=255)),
                ('CodigoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicioLuz.tbclientes')),
            ],
            options={
                'db_table': 'TbDeuda',
            },
        ),
        migrations.CreateModel(
            name='TbPagos',
            fields=[
                ('CodigoPago', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('FechaPago', models.DateField()),
                ('CodigoDeuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServicioLuz.tbdeuda')),
            ],
            options={
                'db_table': 'TbPagos',
            },
        ),
    ]
