# Generated by Django 3.2.10 on 2023-04-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
