# Generated by Django 3.2.10 on 2023-04-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_recibos_agua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciboagua',
            name='consumo',
        ),
        migrations.RemoveField(
            model_name='reciboagua',
            name='direccion',
        ),
    ]
