# Generated by Django 4.2 on 2023-04-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentDeudInter',
            fields=[
                ('CodigoDeudInter', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellido', models.CharField(max_length=255)),
                ('MontoDeuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MontoPago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('FechaVencimientoPago', models.DateField()),
                ('Estado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbCuentaDeudInter',
            },
        ),
    ]
