# Generated by Django 4.2 on 2023-04-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioInternet', '0002_rename_fechavencimientopago_cuentdeudinter_fechvenc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentdeudinter',
            name='CodigoDeudInter',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cuentdeudinter',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
    ]
