# Generated by Django 4.2 on 2023-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioInternet', '0003_alter_cuentdeudinter_codigodeudinter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentdeudinter',
            name='CodigoDeudInter',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
