# Generated by Django 4.2 on 2023-04-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioInternet', '0004_alter_cuentdeudinter_codigodeudinter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentdeudinter',
            name='CodigoDeudInter',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
