# Generated by Django 4.2 on 2023-04-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_plan_cliente_direccion_cliente_servicio_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
